import berkeleydb 


munaciello = """Il munaciello (in napoletano significa "piccolo monaco"), è il personaggio esoterico più noto, temuto e nominato dal popolo partenopeo: uno spiritello bizzarro che si comporta sempre in modo imprevedibile e sul quale sono sorte infinite leggende metropolitane e detti popolari. Al suo comportamento dispettoso spesso si accompagnano benevoli "lasciti" in moneta; ma non bisogna raccontare l'accaduto a nessuno, altrimenti egli si accanirà nei nostri confronti. Non è raro un suo comportamento lascivo nei confronti delle giovani e belle donne.

Il popolo napoletano ha due versioni sulle origini del munaciello. Inizialmente tale figura veniva associata alla Napoli sotterranea, agli antichi gestori dei pozzi d'acqua, i cosiddetti pozzari, che avevano facile accesso alle case passando attraverso i cunicoli che servivano a calare il secchio nei pozzi. I pozzari-munacielli facevano i dispetti nelle abitazioni quando i proprietari dei pozzi non provvedevano a pagarli per i loro servizi. Si tratta di una versione che probabilmente è stata inventata dalla fantasia popolare per dare al munaciello caratteristiche "bonarie".

Accanto ad essa c'è la teoria esoterica che rende il munaciello una presenza demoniaca in veste di frate. Questi tenterebbe ogni volta, con piccoli o grandi doni, di comprarsi un'anima. Questa versione è associata ad una vicenda, svoltasi nel 1445, che narra dell'amore contrastato di due giovani: Catarinella Frezza, figlia di un ricco mercante di stoffe, e Stefano Mariconda, un garzone. Il loro amore finì in tragedia. Stefano venne assassinato nel luogo dove i due innamorati erano soliti incontrarsi in segreto, mentre lei fu rinchiusa in un convento dove diede alla luce un bambino malformato. Le suore del convento adottarono il bambino vestendolo sin da piccolo con abiti monacali e con il cappuccio per mascherarne le deformità. Per le strade di Napoli egli assunse l'appellativo di munaciello. Il bimbo morì in modo misterioso. Sin da subito gli vennero conferiti poteri magici, e la sua figura fu associata alla parte cattiva dell'anima umana, al demonio che si nasconde e che è sempre pronto ad afferrarci."""

mbriana = """L'altra figura di spicco dell'esoterismo napoletano è la bella 'Mbriana. Una romantica leggenda napoletana racconta di una principessa che aveva smarrito la ragione a causa di un amore infelice e vagava per i vicoli della città come un'ombra. Il re, suo padre, per proteggerla ricompensava con doni anonimi quelle case in cui la povera e infelice figlia veniva accolta. Nacque così la leggenda della fortuna legata a questa misteriosa presenza femminile. La bella 'Mbriana, difatti, nell'immaginario del popolo napoletano è lo spirito della casa: essa dimora in maniera fissa in un'abitazione da lei posta sotto la sua protezione. Averla nella propria casa indica benessere e salute.

È difficile descrivere il suo aspetto, perché la creatura appare solo per qualche istante accanto ad una tenda mossa dal vento o nel riflesso della finestra. I napoletani la immaginano come una giovane donna dal viso dolce e sereno, una figura chiara e solare; del resto 'Mbriana (che viene chiamata anche Meriana o 'Mmeriana) deriva dal latino e significa Meridiana, ossia l'ora più luminosa del giorno. A testimonianza dell'affetto verso questa misteriosa figura, a Napoli è molto diffuso il cognome Imbriani, derivante appunto da 'Mbriana.

La leggenda vuole che la bella 'Mbriana sia anche capricciosa, oltre che molto potente, quasi come una dea: porta fortuna a quelli che ama e si vendica verso chi offende la casa posta sotto la sua protezione. I vecchi napoletani consigliano di non lamentarsi mai di una casa troppo piccola o buia e di non fare progetti di trasloco ad alta voce, ma di parlarne sempre fuori casa, in modo da non farsi sentire dalla bella 'Mbriana e non tirarsi addosso le sue ire.

La figura misteriosa, inoltre, ama l'ordine e la pulizia, e per questo si cerca di non trascurare la casa per non renderla irascibile. Un tempo si aveva l'abitudine di mettere a tavola un posto in più per lei con una sedia libera affinché ella potesse entrare e sedersi per riposare."""

uovo_magico = """La leggenda vuole che Publio Virgilio Marone (Mantova, 70 AC - Brindisi, 19 AC), nella sua lunga permanenza a Napoli, abbia creato numerosi oggetti magici benefici (come mosche e serpenti d'oro, che la liberarono dai nocivi), ed in particolare un Uovo magico, sigillato in un vaso in vetro, a sua volta sospeso in una gabbia metallica; il Poeta-Mago lo donò alla città, murandolo in un locale segreto del Castello sito sull'isolotto di Megaride (Castello, sempre secondo la leggenda, da lui stesso costruito, così come la Grotta di Posillipo). Virgilio, inoltre, profetizzò che la presenza dell'Uovo, intatto, avrebbe garantito per sempre alla città la buona sorte, evitando che il suo Castello nel quale era nascosto, assurto a baluardo e simbolo di Napoli, fosse espugnato, e la città conquistata da invasori stranieri; la sua asportazione, o rottura, avrebbe invece provocato innumerevoli disgrazie alla città di Napoli, e, in prospettiva, addirittura la sua distruzione. In conseguenza di ciò Virgilio Mago, che aveva creato un legame ormai indissolubile con la città, fu da allora considerato dai napoletani, anche dopo l'avvento del cristianesimo, protettore e "patrono" di Napoli. Da tale bimillenaria leggenda e dalla profezia del Mago, largamente diffusa e conosciuta, e tenuta in gran conto dal popolo di Napoli, il Castello di Virgilio, che fu ovviamente nei secoli successivi ricostruito e più volte rimaneggiato, prese poi il nome di Castel dell'Ovo, mantenendolo inalterato fino ad oggi.

All'ingresso del Castello si legge peraltro su una lapide in marmo l'epigrafe che segue:

Oro mira novo sic ovo non tuber ovo
Dorica casira cluens futur
Temerare timeto
L'epigrafe, di difficile e molto controversa interpretazione, fu fatta scolpire nel 1370 all'ingresso del Castel dell'Ovo dalla Regina Giovanna I d'Angiò, che dichiarò di aver fatto sostituire l'Uovo di Virgilio, rotto casualmente, si diceva, da un soldato in fuga a seguito dei crolli verificatisi nel Castello per un forte terremoto. Di ciò la Regina, tramite i suoi araldi, diede immediata ampia comunicazione alla popolazione, che tumultuava in tutta la città: essendosi infatti sparsa la voce di una presunta rottura dell'Uovo di Virgilio Mago, che, come si è detto, secondo la più che millenaria leggenda proteggeva Napoli da ogni male, il popolo era terrorizzato dalle conseguenze nefaste per la città che ne sarebbero inevitabilmente seguite. Non è peraltro dimostrato da fonti storiche attendibili che l'Uovo di Virgilio sia effettivamente esistito, né quindi che sia mai stato ritrovato, né tanto meno che esso si sia rotto e sia stato poi sostituito dalla Regina Giovanna."""

storia_marianna = """Sono passati tanti anni ormai, ricordo vagamente le mie vere sembianze, ma chi mi scolpi 2000 anni fa ritenne che io avessi gli occhi grandi, neri, profondi, le labbra piccole ma carnose, la pettinatura in stile greco con le tipiche trecce avvolte sulla testa; avevo trent’anni o poco più, quando mi “immortalarono”.  Dovevo essere molto bella, talmente bella da impersonare l’allegoria della bellezza e dell’amore, Afrodite era il mio nome, ma per altri ero Venere.  Qualcuno vedeva in me anche lo spirito della dea Partenope, la madre dell’antica colonia greca, e mi adorarono come loro fondatrice… o forse ero Cibele, la mamma di Zeus. Ero amata e venerata come una dea, la nostra meravigliosa città era di fondazione greca e andava a divenire uno dei luoghi più importanti del mondo ellenico. Dimoravo in un tempio greco-romano che sorgeva nel cuore del centro storico, in via Anticaglia, il decumano superiore, il quartiere greco per eccellenza.
Ma le mode cambiano, il tempo passa e chi era non lo è piu.

La mia stirpe, quella greca, che mi creò e mi adoro,’ si dimentico’ di me e della sua origine, poco per volta la mia dimora fu abbandonata all’oblio, gli dei persero tutto il loro potere e poco per volta il tempo copri di polvere la mia dimora, e tutto diventò buio.
Passarono gli anni, i secoli, intanto il mondo sopra di me cambiava, anche il popolo cambiava, chissà se aveva ancora bisogno della mia protezione.

Per molti secoli restai al buio, nessuno piu ebbe notizie di me fino a quando, dopo millecinquecento anni, finalmente rividi la luce, ma il mio tempio non esisteva piu e tutto era cambiato attorno a me. Anche il popolo era cambiato, non sentivo piu parlare l’idioma a me caro, quella lingua greca con cui per tanti anni si pregò per me e mi si venero e, dalla vecchia Neapolis, luogo della mia sacralità, mi portarono li dove il sangue del popolo ribolliva di rabbia e rivoluzione, nella zona del mercato, vicino ad un tempio, ma non era il mio e non vi adoravano me, era la chiesa di Sant’Eligio. Ma anche li gli abitanti intuirono qualcosa di magico in me e cominciarono a confidarmi ogni segreto, e a me rivolgevano le loro preghiere, suppliche, offerte, lamentele, preoccupazioni, lacrime, pensieri … credevano che io avessi i doni di preveggenza e parlavano con me aspettando una mia risposta. Ero diventato il simbolo della speranza di tutto il popolo, affranto dalle tante ingiustizie quotidiane. Ma come erano lontani e differenti i tempi classici ed eleganti della mia “Neapolis”, intorno a me ora vedevo solo disperazione, fame.  Ero a piazza Mercato quando nel 1647, durante la rivolta di Masaniello, i soldati spagnoli inferociti dal popolo, mi deturparono il viso poiché ero ormai diventata il simbolo della città e i napoletani, per mio rispetto, proclamarono il lutto cittadino. Ed ero ancora in piazza Mercato, in prima linea, quando nel 1799 i giacobini filofrancesi riconobbero in me “Marianne”, il simbolo femminile nato in seguito alla Rivoluzione Francese, che personificava la nuova Repubblica e i valori sui quali si fondava: libertà, uguaglianza e fratellanza. Una parte dei napoletani mi amava per questo, ma l’altra parte mi odiava, ero il simbolo avverso alla monarchia e nuovamente, nei tumulti che ne seguirono, fui danneggiata e maltrattata. A salvarmi fu come sempre quell’atavico e misterioso senso di rispetto che mi faceva ritenere sacra. Passarono altri 100 anni e fui di nuovo spostata,  venni collocata di fronte alla Chiesa di Santa Maria dell’Avvocata, a pochi metri dalla centralissima Piazza Dante, dove era molto venerato il busto di Sant’Anna; e qui nacque il mio nome attuale, tra la comparazione di Maria Vergine e Anna, e dalla sintesi dei due nomi uscì il mio, Marianna, nome che mi fu definitivamente assegnato, non ero piu la “dea Venere”, ma la popolana “donna Marianna”.  Ormai facevo parte del popolo, non ero piu sull’altare ma tra la gente.
Nel giorno di Sant’Anna, le donne popolane mi abbellivano con nastri e fiori per poi inscenare balletti e danze in mio onore; forse per rendermi partecipe della vita cittadina, vicino agli usi e costumi della nuova Napoli. Passò ancora del tempo, ero ormai abituata alla felice e gioiosa confusione di un vicolo di Napoli, molto differente dalla grigia formalità di un tempio greco, sentivo il chiacchierio delle donne, ero nei giochi dei bambini, ma anche stavolta la mia storia dovette cambiare, e venne la guerra, una guerra crudele e senza limiti. Vidi per la prima volta aerei che sganciavano sulla “mia gente e nei miei vicoli” carichi di morte e distruzioni, tutto crollò intorno a me e anche io fui colpita e danneggiata, e anche stavolta restai cosi per decenni, era ormai il mio destino, affezionarmi al popolo e vederlo morire. Nel 1961 mi prelevarono e restaurarono la mia antica bellezza di dea portandomi in un luogo protetto, forse impietositi dalla mia età, mi chiusero nel museo Filangieri, a due passi dal Duomo. Sarei dovuta essere contenta della mia nuova posizione, dopo 2000 anni finalmente un luogo tranquillo, protetto, ma ero abituata ormai a stare in piazza, ad ascoltare il chiacchiericcio della gente, le suppliche delle popolane, a ricevere le pallonate degli scugnizzi, ad accogliere i colombi su di me e a vedere all’esterno l’alba di un nuovo giorno. Lì nel museo mi sentivo sola e trascurata.  Anche io mancavo al popolo, e nel 2003 crearono una mia copia da esporre li dove avevo passato la mia seconda vita, nel cortile della chiesa di san Giovanni a Mare, vicino piazza Mercato. Rimessa a nuovo, nel 2011 diventai protagonista del Carnevale al Parco Ventaglieri, a Montesanto, che cadde nel giorno dell’8 Marzo, festa della Donna; fui eletta madrina dei festeggiamenti, simbolo antico sacro-profano di Neapolis icona di rinascita della città, a sottolineare il mio destino di madre della città, questa volta non era Venere ad affacciarsi sul mondo, ma la parte di me che ricordava Partenope, la fondatrice di Neapolis. Fortunatamente e con mia grande gioia, pochi anni fa anche dal museo andai via, nonostante le vicissitudini passate, il mio spirito di dea aleggia ancora attorno a me, non piu templi o chiese, non piu piazze e tumulti, ma fui messa li dove oggi dimora il potere. Per chi volesse conoscermi e mostrarmi il suo affetto, oggi può trovarmi nel Palazzo Municipale, sul pianerottolo della prima rampa, da dove, come 2000 anni fa’, veglio e proteggo la mia città."""

dataset = [{"title": "il Munaciello", "text": munaciello},
            {"title": "la Bella 'Mbriana", "text": mbriana},
            {"title": "l'uovo magico di Virgilio", "text": uovo_magico},
            {"title": "la storia di Marianna", "text": storia_marianna}]


database = berkeleydb.hashopen("/home/filippo/Scrivania/Marianna_head/database/wiki_naples_leggende.db", flag="n")

for item in dataset:
    chiave = item["title"].encode("utf-8")
    valore = item["text"].encode("utf-8")
    database[chiave] = valore
    
database.close()
